services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - app_public:/var/www/html/storage/app/public
      - app_private:/var/www/html/storage/app/private
    networks:
      - app-network
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "90:80"
      - "450:443"
    networks:
      - app-network
volumes:
  mysql_data:
  app_public:
  app_private:
networks:
  app-network:
    driver: bridge